### ISSUE TITLE
Unknown assertion

### ISSUE THREAD

**Issue by stlankes** [SFBdragon/talc#12]
Do you know the reason for following message?

`panicked at 'assertion failed: (*self.get_bin_ptr(bin)).is_some()', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/talc-2.2.0/src/lib.rs:184:9`

On aarch64, I get sometimes such assertions? See hermitcore/libhermit-rs#803

**Comment by SFBdragon** [comment]
Meaning: Upon attempting to remove memory from the free list, this assertions checks whether the corresponding bin contains any memory that could be removed at all. More specifically in terms of the code: a request was issued to remove a chunk of bin size x, but the bin corresponding to size x didn't have any memory.

The `deregister` function is called from many places within the allocator for resizing, reserving, and allocating chunks of memory.

Some debugging considerations:
- Did this occur in v2.1 at all? I'd imagine so, no allocator code has changed since (just WASM addons and benchmarks).
- Unless mutual exclusion to the allocator is violated, this probably wasn't caused by the `malloc` function.
- Not thrown by allocator initialization.
- free, grow, shrink, truncate, and extend are fair game. Last I checked libhermit's code, extend and truncate was never used though.
- The free list headers, unlike in v1, are now stored in the heap. It's possible that accidentally overwriting one of the pointers with zero would trick the allocator into thinking a free list is empty. (low likelihood of being relevant? Especially given you've been using v2.*)
- Overwriting any of the size tags within free chunks. (There are two, one is a doubleword up from the bottom, another is immediately below the top. Both are word-size.
- If either of the above are true, it probably happened after any previous use of the allocator, as Talc runs lots of error-checking after every major operation it performs when debug assertions are enabled. Perhaps I should perform such checks beforehand, too, although that would only be useful if you can produce a backtrace. Checking that every bin is empty or nonempty in accordance to the bin occupancy flags is one of those checks, and so is checking that each member of the free lists is in the appropriate bin.
- A double free often would trip a previous check beforehand, but it's not out of the question. A stray free could, but it would require the stray free point near data with particular bits set in order to not fail in other ways. Probably unlikely.


My fuzzing setup is running fine, but I haven't run it on the aarch64 architecture, if there's a possibility of anything architecture specific coming into play. The allocator tests run fine through Miri for MIR targeting aarch64-apple-darwin, but the tests aren't very thorough and such. I'll try to get fuzzing setup for aarch64.

**Comment by mkroening** [comment]
Thanks a lot for your comprehensive reply! I think this has to do with us switching the arena around.

Essentially, we do this:

```rust
let mut talc = Talc::new(InitOnOom::new(span));
let ptr = talc.malloc(layout).unwrap(); // Initializes talc
talc.init(other_span); // Initializes again?
talc.free(ptr, layout); // Problems?
```

Would it make sense that this is the problem?

We have one statically allocated arena for bootstrapping and one arena for the whole heap.
Before, we explicitly switched between two allocators for this, but Stefan tried to avoid this to avoid the extra branch on every allocation.

It makes sense for talc not to support this, probably, so we'll work around this on our part. :)

It might make sense to explicitly document that reinitialization is not supported once there was an allocation, and perhaps also add an assert with a helpful error message in `Talc::init`?

**Comment by SFBdragon** [comment]
This is a perfectly valid use of Talc, and I have intended to support it, but I don't think I've tested doing this yet. I can easily extend the fuzzing script to test this thoroughly though.

I didn't send the previous paragraph earlier, though I'm running the fuzzing tests now. (edit from the future: almost 2mil executions now, seems fine.) 

I've tried getting `cross-rs` to help with testing on aarch64, but unfortunately it doesn't work with `cargo-fuzz`. I don't expect fuzzing on GitHub's CI is a good idea ^-^ I think QEMU should theoretically be able to do what I want but I'm not familiar with it, and I'm a little behind with studies.

If you know the incantations to set up QEMU running aarch64 ubuntu I'd appreciate pointers, but I've arranged to borrow a friend's macbook later today to see if that yields anything.

**Comment by stlankes** [comment]
I changed the PR and used something like this

```
let mut talc = Talc::new(ErrOnOom);
talc.init(new_span); 
let ptr = talc.malloc(layout).unwrap();
talc.extend(other_span); 
talc.free(ptr, layout);
```

This seems to work.

> If you know the incantations to set up QEMU running aarch64 ubuntu I'd appreciate pointers, but I've arranged to borrow a friend's macbook later today to see if that yields anything.

Does [this tutorial ](https://futurewei-cloud.github.io/ARM-Datacenter/qemu/how-to-launch-aarch64-vm/)helps you?

**Comment by SFBdragon** [comment]
Apologies, I've looked through what [mkroening](https://github.com/mkroening) said again and I completely missed the crux. Indeed, the allocator 'forgets' all previous allocations when re-initialized, and so freeing the old allocation would cause exactly the error: the in-heap metadata will still be in the right place, but the control-structure data will disagree. 

This behaviour used to be properly documented in the init function but I ended up removing it for some reason. I'll rewrite the docs to be more clear on this. I've also made a small change to InitOnOom that'll fix some potentially odd behavior, but I don't think you were running into any of that here. new + extend is the way to go though in this case.

> Does [this tutorial ](https://futurewei-cloud.github.io/ARM-Datacenter/qemu/how-to-launch-aarch64-vm/)helps you?

Yes, that should, thanks. I mistakenly dismissed it a few hours ago.

I'll get those changes up soon, but your code looks good to me now. Thank you for your patience and cooperation.

...

(I didn't get nearly enough sleep last night...)

**Comment by SFBdragon** [comment]
At last, I've made a few changes in the new release which have put this to rest. First of all, this requirement for allocations to be only of the current initialization is now documented. Second, a new debug assertion checks if a dealloc/realloc falls outside the arena, which would have made this issue easier to debug in the first place. 

Other than that, I recommend you upgrade to v2.2.1 as libhermit appears to set a minimum alignment to allocations to avoid unnecessary false cache-line sharing. With v2.2.0, this didn't work as well because the allocator would store the allocation tag (metadata) on the cache line below, meaning you could still end up with false sharing when performing allocator operations, potentially hurting performance? I've now overhauled the internal allocation logic to place and use tags above the allocation, which, if placed on a cache line above, would force another aligned allocation to skip that cache line, and wouldn't conflict with the line below, of course. Hopefully this improves SMP allocation performance in libhermit a little. Other than that, there shouldn't be any noticeable difference.

**Comment by mkroening** [comment]
Thank you so much for your help, @SFBdragon! :)

We've just upgraded to talc 2.2.2 after facing some internal issues (https://github.com/hermitcore/libhermit-rs/pull/840).
