### ISSUE TITLE
doc doesn't work on stable

### ISSUE THREAD

**Issue by sehz** [SFBdragon/talc#28]
Using example on doc with std 
```
use talc::*;

static mut ARENA: [u8; 10000] = [0; 10000];

#[global_allocator]
static ALLOCATOR: Talck<spin::Mutex<()>, ClaimOnOom> = Talc::new(unsafe {
    // if we're in a hosted environment, the Rust runtime may allocate before
    // main() is called, so we need to initialize the arena automatically
    ClaimOnOom::new(Span::from_const_array(core::ptr::addr_of!(ARENA)))
}).lock();

fn main() {
    let mut vec = Vec::with_capacity(100);
    vec.extend(0..300usize);
}
```

result in 
```
  |
7 | static ALLOCATOR: Talck<spin::Mutex<()>, ClaimOnOom> = Talc::new(unsafe {
  |                         ^^^^ use of undeclared crate or module `spin`

```

**Comment by SFBdragon** [comment]
This is intentional: Talc doesn't come with a decent lock out of the box so you're expected to bring your own. The `spin` crate's spinlocked mutex is a reasonable choice and what the allocator has been tested with.

Below the example you'll find:

> Note that while the `spin` crate's mutexes are used here, any lock implementing `lock_api` works.

So you'll need to run `cargo add spin` to get the example to work.

If you think anything should be changed, let me know.

**Comment by SFBdragon** [comment]
I'm closing this for now as it has been addressed and has since remained inactive. Please feel free to re-open it or open a new commit though.
